package com.aljoschability.eclipse.tools.mumade.fromc;

import java.util.Collection;

public interface Node {
	public enum Key {
		NO_TYPE, LIST, STR, APOSTROPHE, FOOTER, PARA, PLAIN, LINEBREAK, SPACE, HEADINGSECTION, H1, H2, H3, H4, H5, H6, H7, METADATA, METAKEY, METAVALUE, MATHSPAN, STRONG, EMPH, LINK, SOURCE, TITLE, REFNAME, AUTOLABEL, IMAGE, IMAGEBLOCK, NOTEREFERENCE, CODE, HTML, ELLIPSIS, ENDASH, EMDASH, SINGLEQUOTED, DOUBLEQUOTED, BLOCKQUOTE, BLOCKQUOTEMARKER, RAW, VERBATIM, VERBATIMTYPE, DEFLIST, TERM, DEFINITION, HRULE, ORDEREDLIST, BULLETLIST, LISTITEM, HTMLBLOCK, TABLE, TABLECAPTION, TABLELABEL, TABLESEPARATOR, TABLECELL, CELLSPAN, TABLEROW, TABLEBODY, TABLEHEAD, LINKREFERENCE, NOTESOURCE, CITATIONSOURCE, SOURCEBRANCH, NOTELABEL, ATTRVALUE, ATTRKEY, GLOSSARYSOURCE, GLOSSARYSORTKEY, GLOSSARYTERM, CITATION, NOCITATION, CRITICADDITION, CRITICDELETION, CRITICSUBSTITUTION, CRITICHIGHLIGHT, CRITICCOMMENT, SUPERSCRIPT, SUBSCRIPT, KEY_COUNTER
	}

	Key getKey();

	String getValue();

	Collection<Node> getChildren();

	Node getNext();

	LinkData getLink();
}
